/* eslint-disable */
require('./arrow-down')
require('./arrow-left')
require('./arrow-right')
require('./arrow-up')
require('./email')
require('./key')
require('./lock-unlock')
require('./lock')
require('./logout')
require('./notification')
require('./settings-slider')
require('./social-media-facebook')
require('./social-media-twitter')
require('./trash')
require('./user')
